# Generated by Django 2.1.5 on 2019-03-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('filename', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=256)),
                ('haveher', models.BooleanField()),
                ('good', models.IntegerField()),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('fans', models.IntegerField(default=0)),
            ],
        ),
    ]
