# Generated by Django 2.1.5 on 2019-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
