# Generated by Django 2.1.5 on 2019-03-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_picture_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
        ),
    ]
