# Generated by Django 2.1.5 on 2019-03-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190315_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='userid',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='picture',
            name='good',
            field=models.IntegerField(default=0),
        ),
    ]
