# Generated by Django 2.1.5 on 2019-03-16 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190315_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facefile', models.CharField(max_length=255)),
                ('t_number', models.IntegerField(default=0)),
                ('f_number', models.IntegerField(default=0)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Picture')),
            ],
        ),
    ]
