# Generated by Django 2.1.5 on 2019-03-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_face'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='picture',
        ),
        migrations.AddField(
            model_name='face',
            name='picturefile',
            field=models.CharField(default='', max_length=255),
        ),
    ]
