# Generated by Django 2.1.5 on 2019-03-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190316_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
