# Generated by Django 2.1.5 on 2019-03-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_face_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
